import { FileText, Download, Eye, RefreshCw, HelpCircle } from 'lucide-react';


const Reports = () => {
  const history = [
    { name: 'Final Semester Gradebook', by: 'Sarah Jenkins (Admin)', time: 'Oct 24, 2023 • 14:32', status: 'COMPLETED', actions: ['view', 'download'] },
    { name: 'Mid-Term Compliance Audit', by: 'System Automator', time: 'Oct 24, 2023 • 09:00', status: 'PROCESSING', actions: ['refresh'] },
    { name: 'Student Performance Summary', by: 'Dr. Marcus Webb', time: 'Oct 23, 2023 • 18:15', status: 'FAILED', actions: ['refresh'] },
  ];

  return (
    <div className="space-y-8">


      {/* History Table */}
      <div>
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-medium text-gold">Recent History Log</h3>
          <button className="text-xs font-bold text-sidebar flex items-center gap-1 hover:text-gold transition-colors">
            Export All Logs <Download size={14} />
          </button>
        </div>

        <div className="bg-bg-light rounded-2xl border border-border shadow-sm overflow-hidden">
          <div className="table-responsive"><table className="w-full text-left bg-white min-w-[600px]">
            <thead className="bg-bg-light text-sm font-bold text-sidebar border-b border-border">
              <tr>
                <th className="px-6 py-4">Report Name</th>
                <th className="px-6 py-4">Generated By</th>
                <th className="px-6 py-4">Timestamp</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border text-sm">
              {history.map((item, idx) => (
                <tr key={idx} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      {item.status === 'FAILED' ? <HelpCircle size={18} className="text-sidebar" /> : <FileText size={18} className="text-sidebar" />}
                      <span className="font-medium text-sidebar">{item.name}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-text-main">{item.by}</td>
                  <td className="px-6 py-4 text-text-muted">{item.time}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-bold rounded-full uppercase tracking-wider ${
                      item.status === 'COMPLETED' ? 'bg-green-50 text-green-600' :
                      item.status === 'PROCESSING' ? 'bg-orange-50 text-orange-600' :
                      'bg-red-50 text-red-600'
                    }`}>
                      <div className={`w-1.5 h-1.5 rounded-full ${
                        item.status === 'COMPLETED' ? 'bg-green-500' :
                        item.status === 'PROCESSING' ? 'bg-orange-500' :
                        'bg-red-500'
                      }`}></div>
                      {item.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-3 text-sidebar">
                      {item.actions.includes('view') && <button className="hover:text-gold transition-colors"><Eye size={18} /></button>}
                      {item.actions.includes('download') && <button className="hover:text-gold transition-colors"><Download size={18} /></button>}
                      {item.actions.includes('refresh') && <button className="hover:text-gold transition-colors"><RefreshCw size={18} /></button>}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table></div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
