import { Plus, Settings, ChevronRight, FileText, Download, Eye, RefreshCw, HelpCircle } from 'lucide-react';

const ReportCard = ({ title, format, desc, date }) => (
  <div className="bg-white rounded-2xl shadow-sm border border-border overflow-hidden flex flex-col group cursor-pointer hover:border-gold transition-colors">
    <div className="h-32 bg-sidebar relative overflow-hidden">
      <div className="absolute inset-0 opacity-20 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCI+CjxjaXJjbGUgY3g9IjIiIGN5PSIyIiByPSIyIiBmaWxsPSIjZmZmIi8+Cjwvc3ZnPg==')] bg-repeat"></div>
      <div className="absolute top-4 right-4 bg-white/10 p-2 rounded-full backdrop-blur-sm text-white hover:bg-white/20 transition-colors">
         <Settings size={16} />
      </div>
    </div>
    <div className="p-6 flex-1 flex flex-col">
      <div className="flex justify-between items-start mb-3">
        <h3 className="text-lg font-medium text-sidebar">{title}</h3>
        <span className="text-[10px] font-bold text-text-muted bg-gray-100 px-2 py-1 rounded tracking-wider uppercase">{format}</span>
      </div>
      <p className="text-sm text-text-muted mb-6 line-clamp-3 leading-relaxed">{desc}</p>
      
      <div className="mt-auto flex justify-between items-end">
        <span className="text-xs text-text-muted italic">Last generated {date} ago</span>
        <button className="text-sm font-bold text-sidebar group-hover:text-gold flex items-center gap-1 transition-colors">
          View Full Record <ChevronRight size={16} />
        </button>
      </div>
    </div>
  </div>
);

const Reports = () => {
  const history = [
    { name: 'Final Semester Gradebook', by: 'Sarah Jenkins (Admin)', time: 'Oct 24, 2023 • 14:32', status: 'COMPLETED', actions: ['view', 'download'] },
    { name: 'Mid-Term Compliance Audit', by: 'System Automator', time: 'Oct 24, 2023 • 09:00', status: 'PROCESSING', actions: ['refresh'] },
    { name: 'Student Performance Summary', by: 'Dr. Marcus Webb', time: 'Oct 23, 2023 • 18:15', status: 'FAILED', actions: ['refresh'] },
  ];

  return (
    <div className="space-y-8">
      {/* Header Area */}
      <div className="flex justify-between items-center">
        <div className="flex bg-border p-1 rounded-xl">
          <button className="px-6 py-2.5 text-sm font-bold bg-gold text-sidebar rounded-lg shadow-sm">Standard Templates</button>
          <button className="px-6 py-2.5 text-sm font-bold text-text-muted hover:text-sidebar transition-colors">Custom Reports</button>
        </div>
        <button className="px-5 py-2.5 bg-gold hover:bg-gold-hover text-sidebar rounded-lg text-sm font-bold flex items-center gap-2 transition-colors shadow-sm">
          <Plus size={18} /> Generate New Report
        </button>
      </div>

      {/* Report Cards Grid */}
      <div className="grid grid-cols-3 gap-6">
        <ReportCard 
          title="ECR Standard" 
          format="PDF / XLS" 
          desc="End of Cycle Review comprehensive data including student achievement and growth projections."
          date="2 days"
        />
        <ReportCard 
          title="School Report Card" 
          format="PDF" 
          desc="Official institutional performance summary for board review and public disclosure compliance."
          date="5 days"
        />
        <ReportCard 
          title="Class Funnel" 
          format="INTERACTIVE" 
          desc="Visual breakdown of class progress through curriculum segments with intervention flags."
          date="Automated Daily" // overridden via generic param basically
        />
      </div>

      {/* History Table */}
      <div>
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-medium text-gold">Recent History Log</h3>
          <button className="text-xs font-bold text-sidebar flex items-center gap-1 hover:text-gold transition-colors">
            Export All Logs <Download size={14} />
          </button>
        </div>

        <div className="bg-bg-light rounded-2xl border border-border shadow-sm overflow-hidden">
          <table className="w-full text-left bg-white">
            <thead className="bg-bg-light text-sm font-bold text-sidebar border-b border-border">
              <tr>
                <th className="px-6 py-4">Report Name</th>
                <th className="px-6 py-4">Generated By</th>
                <th className="px-6 py-4">Timestamp</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border text-sm">
              {history.map((item, idx) => (
                <tr key={idx} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      {item.status === 'FAILED' ? <HelpCircle size={18} className="text-sidebar" /> : <FileText size={18} className="text-sidebar" />}
                      <span className="font-medium text-sidebar">{item.name}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-text-main">{item.by}</td>
                  <td className="px-6 py-4 text-text-muted">{item.time}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-bold rounded-full uppercase tracking-wider ${
                      item.status === 'COMPLETED' ? 'bg-green-50 text-green-600' :
                      item.status === 'PROCESSING' ? 'bg-orange-50 text-orange-600' :
                      'bg-red-50 text-red-600'
                    }`}>
                      <div className={`w-1.5 h-1.5 rounded-full ${
                        item.status === 'COMPLETED' ? 'bg-green-500' :
                        item.status === 'PROCESSING' ? 'bg-orange-500' :
                        'bg-red-500'
                      }`}></div>
                      {item.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="flex items-center justify-end gap-3 text-sidebar">
                      {item.actions.includes('view') && <button className="hover:text-gold transition-colors"><Eye size={18} /></button>}
                      {item.actions.includes('download') && <button className="hover:text-gold transition-colors"><Download size={18} /></button>}
                      {item.actions.includes('refresh') && <button className="hover:text-gold transition-colors"><RefreshCw size={18} /></button>}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
